ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('chat/', include("mainchat.urls", namespace="mainchat")),
    path('admin/', admin.site.urls),
]

mainchat/urls.py
# chat/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = "mainchat"

urlpatterns = [
    path("", views.home, name="home"),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('rooms/<str:room_name>/', views.room_view, name='room'),
]

mainchat/models.py
from django.db import models
from django.contrib.auth.models import User


class Room(models.Model):
    name = models.CharField(max_length=120)
    online = models.ManyToManyField(to=User, blank=True)

    # only_staff = models.BooleanField(default=False)

    def get_online_count(self):
        return self.online.count()

    def join(self, user):
        self.online.add(user)
        self.save()

    def leave(self, user):
        self.online.remove(user)
        self.save()

    def __str__(self):
        return f'{self.name} ({self.get_online_count()})'


class Message(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    room = models.ForeignKey(to=Room, on_delete=models.CASCADE)
    content = models.CharField(max_length=512)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.content} [{self.timestamp}]'

mainchat/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from .models import Room
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView


def home(request):
    rooms = Room.objects.all()
    return render(request, "mainchat/index.html", {'rooms': rooms, })


def room_view(request, room_name):
    chat_room, created = Room.objects.get_or_create(name=room_name)
    # staff_room, created = Room.objects.get_or_create(name=room_name, only_staff=True)
    return render(request, 'mainchat/room.html', {'room': chat_room})


class UserRegisterView(SuccessMessageMixin, CreateView):
    form_class = UserCreationForm
    template_name = "mainchat/register.html"
    success_url = reverse_lazy('mainchat:home')
    success_message = "Congrats, you successfully signed up, feel free to use the chat rooms available to you."


class LoginUserView(SuccessMessageMixin, LoginView):
    success_message = "Logged in successfully"
    extra_context = dict(success_url=reverse_lazy('mainchat:home'))

mainchat/templates/mainchat/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>django-channels-chat</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <style>
        #roomSelect {
            height: 300px;
        }
    </style>
</head>
<body>
<div class="container mt-3 p-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-8 text-left">
            <h2 class="text-primary">mm-chat</h2>
        </div>
        <div class="col-4 text-right">
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-primary float-end">
                    <a href="{% url "mainchat:logout" %}" class="fw-bold text-body">Logout</a>
                </button>
            {% else %}
                <button type="button" class="btn btn-primary float-end">
                    <a href="{% url "mainchat:login" %}" class="fw-bold text-body">Login</a>
                </button>
            {% endif %}
            <button type="button" class="btn btn-danger mx-2 float-end">
                <a href="{% url "mainchat:register" %}" class="fw-bold text-body">Sign up</a>
            </button>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-12 col-md-8">
            <div class="mb-2">
                <label for="roomInput">Enter a room name to connect to it:</label>
                <input type="text" class="form-control mt-2" id="roomInput" placeholder="Room name">
                <small id="roomInputHelp" class="form-text text-muted">If the room doesn't exist yet, it will be created
                    for you.</small>
            </div>
            <button type="button" id="roomConnect" class="btn btn-success">Connect</button>
        </div>
        <div class="col-12 col-md-4">
            <label for="roomSelect">Active rooms</label>
            <select multiple class="form-control" id="roomSelect">
                {% for room in rooms %}
                    <option>{{ room }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
</div>
<script src="{% static 'home.js' %}"></script>
</body>
</html>

mainchat/templates/mainchat/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "register.css" %}">
</head>

<body>
<div class="container col vh-100 vw-100 align-items-center gradient-custom">
    <div class="mask d-flex align-items-center h-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-9 col-lg-7 col-xl-7">
                    <div class="card border border-secondary" style="border-radius: 15px;">
                        <div class="card-body p-5">
                            <h2 class="text-uppercase text-center text-success mb-4">Sign Up</h2>
                            <form method="post" action=".">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="d-flex justify-content-center">
                                    <button type="submit"
                                            class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">
                                        Register
                                    </button>
                                </div>
                            </form>
                            <p class="text-muted mt-4 mb-0">
                                Already a user?
                            </p>
                            <a href="{% url "mainchat:home" %}" class="fw-bold text-body">
                                Click here to go back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

mainchat/templates/mainchat/room.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>django-channels-chat</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <style>
            #chatLog {
                height: 300px;
                background-color: #FFFFFF;
                resize: none;
            }

            #onlineUsersSelector {
                height: 300px;
            }
        </style>
    </head>
    <body>
        <div class="container mt-3 p-5">
            <h2>django-channels-chat</h2>
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="mb-2">
                        <label for="chatLog">Room: #{{ room.name }}</label>
                        <textarea class="form-control" id="chatLog" readonly></textarea>
                    </div>
                    <div class="input-group">
                        <input type="text" class="form-control" id="chatMessageInput" placeholder="Enter your chat message">
                        <div class="input-group-append">
                            <button class="btn btn-success" id="chatMessageSend" type="button">Send</button>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <label for="onlineUsers">Online users</label>
                    <select multiple class="form-control" id="onlineUsersSelector">
                    </select>
                </div>
            </div>
            {{ room.name|json_script:"roomName" }}
        </div>
        <script src="{% static 'room.js' %}"></script>
    </body>
</html>